# .github/workflows/ci.yml
name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

permissions:
    contents: read
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Init Repo
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: '22.x'

            - name: Install dependencies
              run: npm ci

            - name: Install vsce
              run: npm install -g vsce

            - name: vsce package
              run: vsce package

            - name: Get extension name
              run: |
                fileName=$(ls -1 *.vsix | head -n 1)
                echo "VSIX_FILE=$fileName" >> $GITHUB_ENV 
                echo "${{ GITHUB_ENV }}"